### ISSUE TITLE
Cast EOCustomObject abstract

### ISSUE THREAD

**Issue by algodata44** [wocommunity/wonder#844]
Hi,

Help please.
I have an Entity Abstract named "EntityAbstract" and a subclass Entity named "EntitySub" where the qualifier is (type='entity-sub').
I have third Entity named "Relation" that has an relationship with "EntityAbstract".

I have a problem when :
```
EOEditingContext eo = ERXEC.newEditingContext();

Relation relation = Relation.fetchRelation(eo, Relation.ID.eq(id));
EntityAbstract entityAbstract = ERXEOControlUtilities.createAndInsertObject(eo, EntityAbstract.class);
entityAbstract.setRelationRelationship(relation);
entityAbstract.setType("entity-sub");
eo.saveChanges();

eo = ERXEC.newEditingContext();

Relation relationFetched = Relation.fetchRelation(eo, Relation.ID.eq(id));
System.err.println(relationFetched.entitySub()); // Print : <EntityAbstract pk:"...">
```

How to print <Entity pk:"..."> and not <EntityAbstract pk:"..."> ?

I don't want use the class "Entity" for ERXEOControlUtilities.createAndInsertObject

Do you have an idea?

I tested :

`eo.invalidateAllObjects();
eo.parentObjectStore().invalidateAllObjects();
eo.rootObjectStore().invalidateAllObjects();`

It does not work...

Thx

**Comment by spelletier** [comment]
Hi,
You did not explained your functional needs so I can only comment the code. 

By definition it is not possible to instantiate an abstract entity (or class). You can only create objects of real complete entities (classes).

I think there is a problem with your model or the way you want to use it.

I use Abstract entities in all my projects (single table flavour). They are really easy to use with Wonder because the framework takes care of adding the restricting qualifier automatically.

The only limit is you cannot change the type of an object (record) with EOF. An EntitySub will remains an EntitySub forever after it's creation.

Samuel

**Comment by algodata44** [comment]
The only limit is you cannot change the type of an object (record) with EOF. An EntitySub will remains an EntitySub forever after it's creation.
> It's true? there is no solution for that?

When I re-compile (after created the EntityAbstract) I have the good result :
`Relation relationFetched = Relation.fetchRelation(eo, Relation.ID.eq(id));
System.err.println(relationFetched.entitySub()); // Print <EntitySub pk:"...">`

Why? How to remove the object from cache? It's possible?

**Comment by spelletier** [comment]
You should explain the problem you try to solve. Changing the class of an existing object make no sense and I do not know any langage that supports that. If you think you need to do that, you probably need to adjust your design. EOF is meant to be used with OO design, you works with objects and the framework manage the reads and writes to the Database.

Maybe ERXPartial would helps if the design cannot change. I never used them but my understanding is they work in a way similar to interfaces in Java. These allows to use an entity X objects as a partial object like a dynamic cast.

**Comment by paulhoadley** [comment]
This sounds like something that @algodata44 should take up on the [mailing list](https://lists.apple.com/mailman/listinfo/webobjects-dev). This isn't really a Wonder _issue_ (in the GitHub sense).

While we're here, though:

> Maybe ERXPartial would helps if the design cannot change. I never used them but my understanding is they work in a way similar to interfaces in Java.

Partial entities are a bit like single table inheritance, but using _composition_ rather than object inheritance. They work great—we've been using them in production for years. If this would help the original poster, we can discuss over on the list.

**Comment by algodata44** [comment]
Thx, ok I will write an email on the mailing list.
Sorry.
